apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalogo
  template:
    metadata:
      labels:
        app: catalogo
    spec:
      containers:
      - name: catalogo-api
        image: fcg-catalogo-api:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: catalogo-service
spec:
  selector:
    app: catalogo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer